#!/bin/bash
#SBATCH --ntasks=16
#SBATCH --time=02:00:00
#SBATCH -mem-per-cpu=2GB

export OMP_NUM_THREADS=16
export OMPI_MCA_rmaps_base_oversubscribe=yes
export OMPI_MCA_mpi_warn_on_fork=0

source setup.sh
cd ~/second_project_gcs/src/
python -u testing_nemesis.py > April_TwentyTwo.txt &
