#!/bin/bash
#SBATCH --ntasks=8
#SBATCH --time=00:30:00
#SBATCH -mem-per-cpu=1GB

export OMP_NUM_THREADS=8
export OMPI_MCA_rmaps_base_oversubscribe=yes
export OMPI_MCA_mpi_warn_on_fork=0

source setup.sh
cd ~/second_project_gcs/src/
python -u testing_nemesis.py > April_TwentyOne.txt &
